name: Swift Package Test

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3
      - name: Run xcode build
        run: |
          xcodebuild -resolvePackageDependencies -scheme SPMSample -project ./SPMSample.xcodeproj
